image: node:6.11.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
  branches:
    development:
      - step:
          caches:
            - node
          script:
            - npm install
            - git clone -b master https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEVELOPMENT_APP_NAME.git heroku
            - npm run build
            - mkdir -p heroku/src
            - cp -rf build/* heroku/src
            - cp -f Procfile heroku
            - cp -f package.json heroku
            - cd heroku && ls -la
            - git add --all || true
            - git config user.email HEROKU_USER_EMAIL
            - git config user.name $HEROKU_USER_NAME
            - git commit -m "pushed by bitbucket pipelines" || true
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEVELOPMENT_APP_NAME.git master --force
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run lint