image: node:6.11.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
  branches:
    master:
      - step:
        script:
            - npm install
            - npm run lint