image: node:6.11.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
  branches:
    development:
      - step:
          caches:
            - node
          script:
#            - npm install
#            - npm run lint
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEVELOPMENT_APP_NAME.git HEAD
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run lint